### ISSUE TITLE
Death of the Dancer does not interrupt song & damage timer

### ISSUE THREAD

**Issue by Pythagorion** [TTT-2/ttt2-wep_dancegun#3]
In my test, the duration was always set to 60 seconds. 

If the dancer dies before the end of the set time, both the song and the damagetick continue until the full 60 seconds are reached. Theoretically, the corpse continues to receive damage. The person even gets damage if they are revived during the time frame. This can also be triggered by damaging the dancer before shooting them with the dancegun.

**Comment by TimGoll** [comment]
I can't reproduce this
If the player dies and the song would normally continue, the sound stops, reving them doesn't change anything
The same holds true for a round end
